---
- hosts: all
  tasks:
    - name: gather package facts 
      package_facts:
        manager: auto 

    - name: Install at if not found  
      yum: 
        name: at 
        state: latest 
      when: 'at' not in ansible_facts['packages'] 
      
    - name: at job that runs after 1 minute and stores current time in a file 
      at: 
        command: "echo $(date) > /tmp/current_date.txt"
        state: present 
        unique: yes 
        units: minutes 
        count: 1 
